export const ANALYTICS_EVENTS = {
  // LAUNCH
  FIRST_LAUNCH: 'FIRST_LAUNCH',
  SESSION_START: 'SESSION_START',

  // NETWORK
  NETWORK_CHANGE: 'NETWORK_CHANGE',

  // BURGER
  BURGER_THEME_CHANGE: 'BURGER_THEME_CHANGE',
  BURGER_LOCALE_CHANGE: 'BURGER_LOCALE_CHANGE',

  // ONBOARDING
  COOKIES_ACCEPT: 'COOKIES_ACCEPT',
  COOKIES_REJECT: 'COOKIES_REJECT',

  // WALLET
  WALLET_OPEN_CONNECT_MODAL: 'WALLET_OPEN_CONNECT_MODAL',
  WALLET_CONNECT: 'WALLET_CONNECT',
  WALLET_CONNECT_ERROR: 'WALLET_CONNECT_ERROR',
  WALLET_CONNECT_INSTALL_EXTENSION: 'WALLET_CONNECT_INSTALL_EXTENSION',
  WALLET_OPEN_DETAILS_MODAL: 'WALLET_OPEN_DETAILS_MODAL',
  WALLET_DISCONNECT: 'WALLET_DISCONNECT',

  // GENERAL
  SELECT_TOKEN: 'SELECT_TOKEN',
  CLICK_MAX_BUTTON: 'CLICK_MAX_BUTTON',

  // SWAP
  SWAP_CLICK_SWITCH: 'SWAP_CLICK_SWITCH',
  SWAP_CLICK_CHANGE_POOL: 'SWAP_CLICK_CHANGE_POOL',
  SWAP_CHANGE_POOL: 'SWAP_CHANGE_POOL',
  SWAP_SUBMIT: 'SWAP_SUBMIT',
  SWAP_CONFIRM: 'SWAP_CONFIRM',
  SWAP_CLOSE_CONFIRM: 'SWAP_CLOSE_CONFIRM',
  SWAP_SIGNED: 'SWAP_SIGNED',
  SWAP_CONFIRM_ERROR: 'SWAP_CONFIRM_ERROR',
  SWAP_SIGNED_ERROR: 'SWAP_SIGNED_ERROR',

  // DEPOSIT
  DEPOSIT_SUBMIT: 'DEPOSIT_SUBMIT',
  DEPOSIT_CONFIRM: 'DEPOSIT_CONFIRM',
  DEPOSIT_SIGNED: 'DEPOSIT_SIGNED',
  DEPOSIT_SIGNED_ERROR: 'DEPOSIT_SIGNED_ERROR',
  DEPOSIT_SELECT_X: 'DEPOSIT_SELECT_X',
  DEPOSIT_SELECT_Y: 'DEPOSIT_SELECT_Y',
  DEPOSIT_INPUT_X: 'DEPOSIT_INPUT_X',
  DEPOSIT_INPUT_Y: 'DEPOSIT_INPUT_Y',
  DEPOSIT_CLICK_25: 'DEPOSIT_CLICK_25',
  DEPOSIT_CLICK_50: 'DEPOSIT_CLICK_50',
  DEPOSIT_CLICK_75: 'DEPOSIT_CLICK_75',
  DEPOSIT_CLICK_100: 'DEPOSIT_CLICK_100',
  DEPOSIT_CLICK_CREATE_POOL: 'DEPOSIT_CLICK_CREATE_POOL',
  DEPOSIT_CLICK_POOL_SELECT: 'DEPOSIT_CLICK_POOL_SELECT',
  DEPOSIT_SELECT_POOL: 'DEPOSIT_SELECT_POOL',

  // REDEEM
  REDEEM_SUBMIT: 'REDEEM_SUBMIT',
  REDEEM_CONFIRM: 'REDEEM_CONFIRM',
  REDEEM_SIGNED: 'REDEEM_SIGNED',
  REDEEM_SIGNED_ERROR: 'REDEEM_SIGNED_ERROR',

  // YIELD FARMING
  FARMS_DEPOSIT: 'FARMS_DEPOSIT',
};
