// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'feedback': string;
  'header': string;
  'logotype': string;
  'main': string;
  'rightsideItem': string;
  'tools': string;
}
export const cssExports: CssExports;
export default cssExports;
