// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'header': string;
  'logotype': string;
  'main': string;
  'rightside': string;
  'rightsideItem': string;
}
export const cssExports: CssExports;
export default cssExports;
