import './Icon.stories.scss';

import { Meta, Story } from '@storybook/react';
import React from 'react';

import * as Icon from './Icon';

export default {
  title: 'Components/Icon',
  component: Icon.IconProvider,
} as Meta<typeof Icon.IconProvider>;

const OutlinedTemplate: Story = () => (
  <div>
    <h3>Outlined</h3>
    <h4>Directional</h4>
    <div className="icons">
      <Icon.StepBackwardOutlined />
      <Icon.StepForwardOutlined />
      <Icon.FastBackwardOutlined />
      <Icon.FastForwardOutlined />
      <Icon.ShrinkOutlined />
      <Icon.ArrowsAltOutlined />
      <Icon.DownOutlined />
      <Icon.UpOutlined />
      <Icon.LeftOutlined />
      <Icon.RightOutlined />
      <Icon.CaretUpOutlined />
      <Icon.CaretDownOutlined />
      <Icon.CaretLeftOutlined />
      <Icon.CaretRightOutlined />
      <Icon.UpCircleOutlined />
      <Icon.DownCircleOutlined />
      <Icon.LeftCircleOutlined />
      <Icon.RightCircleOutlined />
      <Icon.DoubleRightOutlined />
      <Icon.DoubleLeftOutlined />
      <Icon.VerticalLeftOutlined />
      <Icon.VerticalRightOutlined />
      <Icon.VerticalAlignTopOutlined />
      <Icon.VerticalAlignMiddleOutlined />
      <Icon.VerticalAlignBottomOutlined />
      <Icon.ForwardOutlined />
      <Icon.BackwardOutlined />
      <Icon.RollbackOutlined />
      <Icon.EnterOutlined />
      <Icon.RetweetOutlined />
      <Icon.SwapOutlined />
      <Icon.SwapLeftOutlined />
      <Icon.SwapRightOutlined />
      <Icon.ArrowUpOutlined />
      <Icon.ArrowDownOutlined />
      <Icon.ArrowLeftOutlined />
      <Icon.ArrowRightOutlined />
      <Icon.PlayCircleOutlined />
      <Icon.UpSquareOutlined />
      <Icon.DownSquareOutlined />
      <Icon.LeftSquareOutlined />
      <Icon.RightSquareOutlined />
      <Icon.LoginOutlined />
      <Icon.LogoutOutlined />
      <Icon.MenuFoldOutlined />
      <Icon.MenuUnfoldOutlined />
      <Icon.BorderBottomOutlined />
      <Icon.BorderHorizontalOutlined />
      <Icon.BorderInnerOutlined />
      <Icon.BorderOuterOutlined />
      <Icon.BorderLeftOutlined />
      <Icon.BorderRightOutlined />
      <Icon.BorderTopOutlined />
      <Icon.BorderVerticleOutlined />
      <Icon.PicCenterOutlined />
      <Icon.PicLeftOutlined />
      <Icon.PicRightOutlined />
      <Icon.RadiusBottomrightOutlined />
      <Icon.RadiusBottomrightOutlined />
      <Icon.RadiusUpleftOutlined />
      <Icon.RadiusUprightOutlined />
      <Icon.FullscreenOutlined />
      <Icon.FullscreenExitOutlined />
    </div>
    <h4>Suggested</h4>
    <div className="icons">
      <Icon.QuestionOutlined />
      <Icon.QuestionCircleOutlined />
      <Icon.PlusOutlined />
      <Icon.PlusCircleOutlined />
      <Icon.PauseOutlined />
      <Icon.PauseCircleOutlined />
      <Icon.MinusOutlined />
      <Icon.MinusCircleOutlined />
      <Icon.PlusSquareOutlined />
      <Icon.MinusSquareOutlined />
      <Icon.InfoOutlined />
      <Icon.InfoCircleOutlined />
      <Icon.ExclamationOutlined />
      <Icon.ExclamationCircleOutlined />
      <Icon.CloseOutlined />
      <Icon.CloseCircleOutlined />
      <Icon.CloseSquareOutlined />
      <Icon.CheckOutlined />
      <Icon.CheckCircleOutlined />
      <Icon.CheckSquareOutlined />
      <Icon.ClockCircleOutlined />
      <Icon.WarningOutlined />
      <Icon.IssuesCloseOutlined />
      <Icon.StopOutlined />
    </div>
    <h4>Editor</h4>
    <div className="icons">
      <Icon.EditOutlined />
      <Icon.FormOutlined />
      <Icon.CopyOutlined />
      <Icon.ScissorOutlined />
      <Icon.DeleteOutlined />
      <Icon.SnippetsOutlined />
      <Icon.DiffOutlined />
      <Icon.HighlightOutlined />
      <Icon.AlignCenterOutlined />
      <Icon.AlignLeftOutlined />
      <Icon.AlignRightOutlined />
      <Icon.BgColorsOutlined />
      <Icon.BoldOutlined />
      <Icon.ItalicOutlined />
      <Icon.UnderlineOutlined />
      <Icon.StrikethroughOutlined />
      <Icon.RedoOutlined />
      <Icon.UndoOutlined />
      <Icon.ZoomInOutlined />
      <Icon.ZoomOutOutlined />
      <Icon.FontColorsOutlined />
      <Icon.FontSizeOutlined />
      <Icon.LineHeightOutlined />
      <Icon.DashOutlined />
      <Icon.SmallDashOutlined />
      <Icon.SortAscendingOutlined />
      <Icon.SortDescendingOutlined />
      <Icon.DragOutlined />
      <Icon.OrderedListOutlined />
      <Icon.UnorderedListOutlined />
      <Icon.RadiusSettingOutlined />
      <Icon.ColumnWidthOutlined />
      <Icon.ColumnHeightOutlined />
    </div>
    <h4>Data</h4>
    <div className="icons">
      <Icon.AreaChartOutlined />
      <Icon.PieChartOutlined />
      <Icon.BarChartOutlined />
      <Icon.DotChartOutlined />
      <Icon.LineChartOutlined />
      <Icon.RadarChartOutlined />
      <Icon.HeatMapOutlined />
      <Icon.FallOutlined />
      <Icon.RiseOutlined />
      <Icon.StockOutlined />
      <Icon.BoxPlotOutlined />
      <Icon.FundOutlined />
      <Icon.SlidersOutlined />
    </div>
    <h4>Brand and Logos</h4>
    <div className="icons">
      <Icon.AndroidOutlined />
      <Icon.AppleOutlined />
      <Icon.WindowsOutlined />
      <Icon.IeOutlined />
      <Icon.ChromeOutlined />
      <Icon.GithubOutlined />
      <Icon.AliwangwangOutlined />
      <Icon.DingdingOutlined />
      <Icon.WeiboSquareOutlined />
      <Icon.WeiboCircleOutlined />
      <Icon.TaobaoCircleOutlined />
      <Icon.Html5Outlined />
      <Icon.WeiboOutlined />
      <Icon.TwitterOutlined />
      <Icon.WechatOutlined />
      <Icon.YoutubeOutlined />
      <Icon.AlipayCircleOutlined />
      <Icon.TaobaoOutlined />
      <Icon.SkypeOutlined />
      <Icon.QqOutlined />
      <Icon.MediumWorkmarkOutlined />
      <Icon.GitlabOutlined />
      <Icon.MediumOutlined />
      <Icon.LinkedinOutlined />
      <Icon.GooglePlusOutlined />
      <Icon.DropboxOutlined />
      <Icon.FacebookOutlined />
      <Icon.CodepenOutlined />
      <Icon.CodeSandboxOutlined />
      <Icon.AmazonOutlined />
      <Icon.GoogleOutlined />
      <Icon.CodepenCircleOutlined />
      <Icon.AlipayOutlined />
      <Icon.AntDesignOutlined />
      <Icon.AntCloudOutlined />
      <Icon.AliyunOutlined />
      <Icon.ZhihuOutlined />
      <Icon.SlackOutlined />
      <Icon.SlackSquareOutlined />
      <Icon.BehanceOutlined />
      <Icon.BehanceSquareOutlined />
      <Icon.DribbbleOutlined />
      <Icon.DribbbleSquareOutlined />
      <Icon.InstagramOutlined />
      <Icon.YuqueOutlined />
      <Icon.AlibabaOutlined />
      <Icon.YahooOutlined />
      <Icon.RedditOutlined />
      <Icon.SketchOutlined />
    </div>
    <h4>Application</h4>
    <div className="icons">
      <Icon.AccountBookOutlined />
      <Icon.AimOutlined />
      <Icon.AlertOutlined />
      <Icon.ApartmentOutlined />
      <Icon.ApiOutlined />
      <Icon.AppstoreAddOutlined />
      <Icon.AppstoreOutlined />
      <Icon.AudioOutlined />
      <Icon.AudioMutedOutlined />
      <Icon.AuditOutlined />
      <Icon.BankOutlined />
      <Icon.BarcodeOutlined />
      <Icon.BarsOutlined />
      <Icon.BellOutlined />
      <Icon.BlockOutlined />
      <Icon.BookOutlined />
      <Icon.BorderOutlined />
      <Icon.BorderlessTableOutlined />
      <Icon.BranchesOutlined />
      <Icon.BugOutlined />
      <Icon.BuildOutlined />
      <Icon.BulbOutlined />
      <Icon.CalculatorOutlined />
      <Icon.CalendarOutlined />
      <Icon.CameraOutlined />
      <Icon.CarOutlined />
      <Icon.CarryOutOutlined />
      <Icon.CiCircleOutlined />
      <Icon.CiOutlined />
      <Icon.ClearOutlined />
      <Icon.CloudDownloadOutlined />
      <Icon.CloudOutlined />
      <Icon.CloudServerOutlined />
      <Icon.CloudSyncOutlined />
      <Icon.CloudUploadOutlined />
      <Icon.ClusterOutlined />
      <Icon.CodeOutlined />
      <Icon.CoffeeOutlined />
      <Icon.CommentOutlined />
      <Icon.CompassOutlined />
      <Icon.ConsoleSqlOutlined />
      <Icon.ContactsOutlined />
      <Icon.ContainerOutlined />
      <Icon.ControlOutlined />
      <Icon.CopyrightOutlined />
      <Icon.CreditCardOutlined />
      <Icon.CrownOutlined />
      <Icon.CustomerServiceOutlined />
      <Icon.DashboardOutlined />
      <Icon.DatabaseOutlined />
      <Icon.DeleteColumnOutlined />
      <Icon.DeleteRowOutlined />
      <Icon.DeliveredProcedureOutlined />
      <Icon.DeploymentUnitOutlined />
      <Icon.DesktopOutlined />
      <Icon.DingtalkOutlined />
      <Icon.DisconnectOutlined />
      <Icon.DislikeOutlined />
      <Icon.DollarCircleOutlined />
      <Icon.DollarOutlined />
      <Icon.DownloadOutlined />
      <Icon.EllipsisOutlined />
      <Icon.EnvironmentOutlined />
      <Icon.EuroCircleOutlined />
      <Icon.EuroOutlined />
      <Icon.ExceptionOutlined />
      <Icon.ExpandAltOutlined />
      <Icon.ExpandOutlined />
      <Icon.ExperimentOutlined />
      <Icon.ExportOutlined />
      <Icon.EyeOutlined />
      <Icon.EyeInvisibleOutlined />
      <Icon.FieldBinaryOutlined />
      <Icon.FieldNumberOutlined />
      <Icon.FieldStringOutlined />
      <Icon.FieldTimeOutlined />
      <Icon.FileAddOutlined />
      <Icon.FileDoneOutlined />
      <Icon.FileExcelOutlined />
      <Icon.FileExclamationFilled />
      <Icon.FileOutlined />
      <Icon.FileGifOutlined />
      <Icon.FileImageOutlined />
      <Icon.FileJpgOutlined />
      <Icon.FileMarkdownOutlined />
      <Icon.FilePdfOutlined />
      <Icon.FilePptOutlined />
      <Icon.FileProtectOutlined />
      <Icon.FileSearchOutlined />
      <Icon.FileSyncOutlined />
      <Icon.FileTextOutlined />
      <Icon.FileUnknownOutlined />
      <Icon.FileWordOutlined />
      <Icon.FileZipOutlined />
      <Icon.FilterOutlined />
      <Icon.FireOutlined />
      <Icon.FlagOutlined />
      <Icon.FolderAddOutlined />
      <Icon.FolderOutlined />
      <Icon.FolderOpenOutlined />
      <Icon.FolderViewOutlined />
      <Icon.ForkOutlined />
      <Icon.FormatPainterOutlined />
      <Icon.FrownOutlined />
      <Icon.FunctionOutlined />
      <Icon.FundProjectionScreenOutlined />
      <Icon.FundViewOutlined />
      <Icon.FunnelPlotOutlined />
      <Icon.GatewayOutlined />
      <Icon.GiftOutlined />
      <Icon.GiftOutlined />
      <Icon.GlobalOutlined />
      <Icon.GoldOutlined />
      <Icon.GroupOutlined />
      <Icon.HddOutlined />
      <Icon.HeartOutlined />
      <Icon.HistoryOutlined />
      <Icon.HomeOutlined />
      <Icon.HourglassOutlined />
      <Icon.IdcardOutlined />
      <Icon.ImportOutlined />
      <Icon.InboxOutlined />
      <Icon.InsertRowAboveOutlined />
      <Icon.InsertRowBelowOutlined />
      <Icon.InsertRowLeftOutlined />
      <Icon.InsertRowRightOutlined />
      <Icon.InsuranceOutlined />
      <Icon.KeyOutlined />
      <Icon.LaptopOutlined />
      <Icon.LayoutOutlined />
      <Icon.LikeOutlined />
      <Icon.LineOutlined />
      <Icon.LinkOutlined />
      <Icon.Loading3QuartersOutlined />
      <Icon.LoadingOutlined />
      <Icon.LockOutlined />
      <Icon.MacCommandOutlined />
      <Icon.MailOutlined />
      <Icon.ManOutlined />
      <Icon.MedicineBoxOutlined />
      <Icon.MehOutlined />
      <Icon.MenuOutlined />
      <Icon.MergeCellsOutlined />
      <Icon.MessageOutlined />
      <Icon.MobileOutlined />
      <Icon.MoneyCollectOutlined />
      <Icon.MonitorOutlined />
      <Icon.MoreOutlined />
      <Icon.NodeCollapseOutlined />
      <Icon.NodeExpandOutlined />
      <Icon.NodeIndexOutlined />
      <Icon.NotificationOutlined />
      <Icon.NumberOutlined />
      <Icon.OneToOneOutlined />
      <Icon.PaperClipOutlined />
      <Icon.PartitionOutlined />
      <Icon.PayCircleOutlined />
      <Icon.PercentageOutlined />
      <Icon.PhoneOutlined />
      <Icon.PictureOutlined />
      <Icon.PlaySquareOutlined />
      <Icon.PoundCircleOutlined />
      <Icon.PoundOutlined />
      <Icon.PoweroffOutlined />
      <Icon.PrinterOutlined />
      <Icon.ProfileOutlined />
      <Icon.ProjectOutlined />
      <Icon.PropertySafetyFilled />
      <Icon.PullRequestOutlined />
      <Icon.PushpinOutlined />
      <Icon.QrcodeOutlined />
      <Icon.ReadOutlined />
      <Icon.ReconciliationOutlined />
      <Icon.RedEnvelopeOutlined />
      <Icon.ReloadOutlined />
      <Icon.RestOutlined />
      <Icon.RobotOutlined />
      <Icon.RocketOutlined />
      <Icon.RotateLeftOutlined />
      <Icon.RotateRightOutlined />
      <Icon.SafetyCertificateOutlined />
      <Icon.SafetyOutlined />
      <Icon.SaveOutlined />
      <Icon.ScanOutlined />
      <Icon.ScheduleOutlined />
      <Icon.SearchOutlined />
      <Icon.SecurityScanOutlined />
      <Icon.SelectOutlined />
      <Icon.SendOutlined />
      <Icon.SettingOutlined />
      <Icon.ShakeOutlined />
      <Icon.ShareAltOutlined />
      <Icon.ShopOutlined />
      <Icon.ShoppingCartOutlined />
      <Icon.ShoppingOutlined />
      <Icon.SisternodeOutlined />
      <Icon.SkinOutlined />
      <Icon.SmileOutlined />
      <Icon.SolutionOutlined />
      <Icon.SoundOutlined />
      <Icon.SplitCellsOutlined />
      <Icon.StarOutlined />
      <Icon.SubnodeOutlined />
      <Icon.SwitcherOutlined />
      <Icon.SyncOutlined />
      <Icon.TableOutlined />
      <Icon.TabletOutlined />
      <Icon.TagOutlined />
      <Icon.TagsOutlined />
      <Icon.TeamOutlined />
      <Icon.ThunderboltOutlined />
      <Icon.ToTopOutlined />
      <Icon.ToolOutlined />
      <Icon.TrademarkCircleOutlined />
      <Icon.TrademarkOutlined />
      <Icon.TransactionOutlined />
      <Icon.TranslationOutlined />
      <Icon.TrophyOutlined />
      <Icon.UngroupOutlined />
      <Icon.UnlockOutlined />
      <Icon.UploadOutlined />
      <Icon.UsbOutlined />
      <Icon.UserAddOutlined />
      <Icon.UserDeleteOutlined />
      <Icon.UserOutlined />
      <Icon.UserSwitchOutlined />
      <Icon.UsergroupAddOutlined />
      <Icon.UsergroupDeleteOutlined />
      <Icon.VerifiedOutlined />
      <Icon.VideoCameraAddOutlined />
      <Icon.VideoCameraOutlined />
      <Icon.WalletOutlined />
      <Icon.WhatsAppOutlined />
      <Icon.WifiOutlined />
      <Icon.WomanOutlined />
    </div>
  </div>
);

const SolidTemplate: Story = () => (
  <div>
    <h3>Solid</h3>
    <h4>Directional</h4>
    <div className="icons">
      <Icon.StepBackwardFilled />
      <Icon.StepForwardFilled />
      <Icon.FastBackwardFilled />
      <Icon.FastForwardFilled />
      <Icon.CaretUpFilled />
      <Icon.CaretDownFilled />
      <Icon.CaretLeftFilled />
      <Icon.CaretRightFilled />
      <Icon.UpCircleFilled />
      <Icon.DownCircleFilled />
      <Icon.LeftCircleFilled />
      <Icon.RightCircleFilled />
      <Icon.ForwardFilled />
      <Icon.BackwardFilled />
      <Icon.PlayCircleFilled />
      <Icon.UpSquareFilled />
      <Icon.DownSquareFilled />
      <Icon.LeftSquareFilled />
      <Icon.RightSquareFilled />
    </div>
    <h4>Suggested</h4>
    <div className="icons">
      <Icon.QuestionCircleFilled />
      <Icon.PlusCircleFilled />
      <Icon.PauseCircleFilled />
      <Icon.MinusCircleFilled />
      <Icon.MinusSquareFilled />
      <Icon.InfoCircleFilled />
      <Icon.ExclamationCircleOutlined />
      <Icon.CloseCircleFilled />
      <Icon.CloseSquareFilled />
      <Icon.CheckCircleFilled />
      <Icon.CheckSquareFilled />
      <Icon.ClockCircleFilled />
      <Icon.WarningFilled />
      <Icon.StopFilled />
    </div>
    <h4>Editor</h4>
    <div className="icons">
      <Icon.EditFilled />
      <Icon.CopyFilled />
      <Icon.DeleteFilled />
      <Icon.SnippetsFilled />
      <Icon.DiffFilled />
      <Icon.HighlightFilled />
    </div>
    <h4>Data</h4>
    <div className="icons">
      <Icon.PieChartFilled />
      <Icon.BoxPlotFilled />
      <Icon.FundFilled />
      <Icon.SlidersFilled />
    </div>
    <h4>Brand and Logos</h4>
    <div className="icons">
      <Icon.AndroidFilled />
      <Icon.AppleFilled />
      <Icon.WindowsFilled />
      <Icon.ChromeFilled />
      <Icon.GithubFilled />
      <Icon.AliwangwangFilled />
      <Icon.WeiboSquareFilled />
      <Icon.WeiboCircleFilled />
      <Icon.TaobaoCircleFilled />
      <Icon.Html5Filled />
      <Icon.WechatFilled />
      <Icon.YoutubeFilled />
      <Icon.AlipayCircleFilled />
      <Icon.SkypeFilled />
      <Icon.GithubFilled />
      <Icon.LinkedinFilled />
      <Icon.FacebookFilled />
      <Icon.CodeSandboxCircleFilled />
      <Icon.CodepenCircleFilled />
      <Icon.SlackSquareFilled />
      <Icon.BehanceSquareFilled />
      <Icon.DribbbleSquareFilled />
      <Icon.InstagramFilled />
      <Icon.YuqueFilled />
      <Icon.YahooFilled />
    </div>
    <h4>Application</h4>
    <div className="icons">
      <Icon.AccountBookFilled />
      <Icon.AlertFilled />
      <Icon.AlipaySquareFilled />
      <Icon.AmazonCircleFilled />
      <Icon.AmazonSquareFilled />
      <Icon.ApiFilled />
      <Icon.AppstoreFilled />
      <Icon.AudioFilled />
      <Icon.BankFilled />
      <Icon.BehanceCircleFilled />
      <Icon.BellFilled />
      <Icon.BookFilled />
      <Icon.BugFilled />
      <Icon.BuildFilled />
      <Icon.BulbFilled />
      <Icon.CalculatorFilled />
      <Icon.CalendarFilled />
      <Icon.CameraFilled />
      <Icon.CarFilled />
      <Icon.CarryOutFilled />
      <Icon.CiCircleFilled />
      <Icon.CloudFilled />
      <Icon.CodeFilled />
      <Icon.CodeSandboxSquareFilled />
      <Icon.CodepenSquareFilled />
      <Icon.CompassFilled />
      <Icon.ContactsFilled />
      <Icon.ContainerFilled />
      <Icon.ControlFilled />
      <Icon.CreditCardFilled />
      <Icon.CrownFilled />
      <Icon.CustomerServiceFilled />
      <Icon.DashboardFilled />
      <Icon.DatabaseFilled />
      <Icon.DingtalkCircleFilled />
      <Icon.DingtalkSquareFilled />
      <Icon.DislikeFilled />
      <Icon.DollarCircleFilled />
      <Icon.DribbbleCircleFilled />
      <Icon.DropboxCircleFilled />
      <Icon.DropboxSquareFilled />
      <Icon.EnvironmentFilled />
      <Icon.EuroCircleFilled />
      <Icon.ExperimentFilled />
      <Icon.EyeFilled />
      <Icon.EyeInvisibleFilled />
      <Icon.FileAddFilled />
      <Icon.FileExcelFilled />
      <Icon.FileExclamationFilled />
      <Icon.FileFilled />
      <Icon.FileImageFilled />
      <Icon.FileMarkdownFilled />
      <Icon.FilePdfFilled />
      <Icon.FilePptFilled />
      <Icon.FileTextFilled />
      <Icon.FileUnknownFilled />
      <Icon.FileWordFilled />
      <Icon.FileZipFilled />
      <Icon.FilterFilled />
      <Icon.FireFilled />
      <Icon.FlagFilled />
      <Icon.FolderAddFilled />
      <Icon.FolderFilled />
      <Icon.FolderOpenFilled />
      <Icon.FormatPainterFilled />
      <Icon.FrownFilled />
      <Icon.FunnelPlotFilled />
      <Icon.GiftFilled />
      <Icon.GoldFilled />
      <Icon.GoldenFilled />
      <Icon.GoogleCircleFilled />
      <Icon.GooglePlusCircleFilled />
      <Icon.GooglePlusSquareFilled />
      <Icon.GoogleSquareFilled />
      <Icon.HddFilled />
      <Icon.HeartFilled />
      <Icon.HomeFilled />
      <Icon.HourglassFilled />
      <Icon.IdcardFilled />
      <Icon.IeCircleFilled />
      <Icon.IeSquareFilled />
      <Icon.InsuranceFilled />
      <Icon.InteractionFilled />
      <Icon.LayoutFilled />
      <Icon.LikeFilled />
      <Icon.LockFilled />
      <Icon.MacCommandOutlined />
      <Icon.MailFilled />
      <Icon.MedicineBoxFilled />
      <Icon.MediumCircleFilled />
      <Icon.MediumSquareFilled />
      <Icon.MehFilled />
      <Icon.MessageFilled />
      <Icon.MobileFilled />
      <Icon.MoneyCollectFilled />
      <Icon.NotificationFilled />
      <Icon.PayCircleFilled />
      <Icon.PhoneFilled />
      <Icon.PictureFilled />
      <Icon.PlaySquareFilled />
      <Icon.PoundCircleFilled />
      <Icon.PrinterFilled />
      <Icon.ProfileFilled />
      <Icon.ProjectFilled />
      <Icon.PropertySafetyFilled />
      <Icon.PushpinFilled />
      <Icon.QqCircleFilled />
      <Icon.QqSquareFilled />
      <Icon.ReadFilled />
      <Icon.ReconciliationFilled />
      <Icon.RedEnvelopeOutlined />
      <Icon.RedditCircleFilled />
      <Icon.RedditSquareFilled />
      <Icon.RestFilled />
      <Icon.RobotFilled />
      <Icon.RocketFilled />
      <Icon.SafetyCertificateFilled />
      <Icon.SaveFilled />
      <Icon.ScheduleFilled />
      <Icon.SecurityScanFilled />
      <Icon.SettingFilled />
      <Icon.ShopFilled />
      <Icon.ShoppingFilled />
      <Icon.SignalFilled />
      <Icon.SketchCircleFilled />
      <Icon.SketchSquareFilled />
      <Icon.SkinFilled />
      <Icon.SlackCircleFilled />
      <Icon.SmileFilled />
      <Icon.SoundFilled />
      <Icon.StarFilled />
      <Icon.SwitcherFilled />
      <Icon.TabletFilled />
      <Icon.TagFilled />
      <Icon.TagsFilled />
      <Icon.TaobaoSquareFilled />
      <Icon.ThunderboltOutlined />
      <Icon.ToolFilled />
      <Icon.TrademarkCircleFilled />
      <Icon.TrophyFilled />
      <Icon.TwitterCircleFilled />
      <Icon.TwitterSquareFilled />
      <Icon.UnlockFilled />
      <Icon.UsbFilled />
      <Icon.VideoCameraFilled />
      <Icon.WalletFilled />
      <Icon.ZhihuCircleFilled />
      <Icon.ZhihuSquareFilled />
    </div>
  </div>
);

const TwoToneTemplate: Story = () => (
  <div>
    <h3>Two Tone</h3>
    <h4>Directional</h4>
    <div className="icons">
      <Icon.UpCircleTwoTone />
      <Icon.DownCircleTwoTone />
      <Icon.LeftCircleTwoTone />
      <Icon.RightSquareTwoTone />
      <Icon.PlayCircleTwoTone />
      <Icon.UpSquareTwoTone />
      <Icon.DownSquareTwoTone />
      <Icon.LeftSquareTwoTone />
      <Icon.RightSquareTwoTone />
    </div>
    <h4>Suggested</h4>
    <div className="icons">
      <Icon.QuestionCircleTwoTone />
      <Icon.PlusCircleTwoTone />
      <Icon.PauseCircleTwoTone />
      <Icon.MinusCircleTwoTone />
      <Icon.PlusCircleTwoTone />
      <Icon.MinusSquareTwoTone />
      <Icon.InfoCircleTwoTone />
      <Icon.ExclamationCircleTwoTone />
      <Icon.CloseCircleTwoTone />
      <Icon.CloseSquareTwoTone />
      <Icon.CheckCircleTwoTone />
      <Icon.CheckSquareTwoTone />
      <Icon.ClockCircleTwoTone />
      <Icon.WarningTwoTone />
      <Icon.StopTwoTone />
    </div>
    <h4>Editor</h4>
    <div className="icons">
      <Icon.EditTwoTone />
      <Icon.CopyTwoTone />
      <Icon.DeleteTwoTone />
      <Icon.SnippetsTwoTone />
      <Icon.DiffTwoTone />
      <Icon.HighlightTwoTone />
    </div>
    <h4>Data</h4>
    <div className="icons">
      <Icon.PieChartTwoTone />
      <Icon.BoxPlotTwoTone />
      <Icon.FundTwoTone />
      <Icon.SlidersTwoTone />
    </div>
    <h4>Brand and Logos</h4>
    <div className="icons">
      <Icon.Html5TwoTone />
    </div>
    <h4>Application</h4>
    <div className="icons">
      <Icon.AccountBookTwoTone />
      <Icon.AlertTwoTone />
      <Icon.ApiTwoTone />
      <Icon.AppstoreTwoTone />
      <Icon.AudioTwoTone />
      <Icon.BankTwoTone />
      <Icon.BellTwoTone />
      <Icon.BookTwoTone />
      <Icon.BugTwoTone />
      <Icon.BuildTwoTone />
      <Icon.BulbTwoTone />
      <Icon.CalculatorTwoTone />
      <Icon.CalendarTwoTone />
      <Icon.CameraTwoTone />
      <Icon.CarTwoTone />
      <Icon.CarryOutTwoTone />
      <Icon.CiCircleTwoTone />
      <Icon.CiTwoTone />
      <Icon.CloudTwoTone />
      <Icon.CodeTwoTone />
      <Icon.CompassTwoTone />
      <Icon.ContactsTwoTone />
      <Icon.ContainerTwoTone />
      <Icon.ControlTwoTone />
      <Icon.CopyrightTwoTone />
      <Icon.CreditCardTwoTone />
      <Icon.CrownTwoTone />
      <Icon.CustomerServiceTwoTone />
      <Icon.DashboardTwoTone />
      <Icon.DatabaseTwoTone />
      <Icon.DislikeTwoTone />
      <Icon.DollarCircleTwoTone />
      <Icon.DollarTwoTone />
      <Icon.EnvironmentTwoTone />
      <Icon.EuroCircleTwoTone />
      <Icon.EuroTwoTone />
      <Icon.ExperimentTwoTone />
      <Icon.EyeTwoTone />
      <Icon.EyeInvisibleTwoTone />
      <Icon.FileAddTwoTone />
      <Icon.FileExcelTwoTone />
      <Icon.FileExclamationTwoTone />
      <Icon.FileTwoTone />
      <Icon.FileImageTwoTone />
      <Icon.FileMarkdownTwoTone />
      <Icon.FilePdfTwoTone />
      <Icon.FilePptTwoTone />
      <Icon.FileTextTwoTone />
      <Icon.FileUnknownTwoTone />
      <Icon.FileWordTwoTone />
      <Icon.FileZipTwoTone />
      <Icon.FilterTwoTone />
      <Icon.FireTwoTone />
      <Icon.FlagTwoTone />
      <Icon.FolderAddTwoTone />
      <Icon.FolderTwoTone />
      <Icon.FolderOpenTwoTone />
      <Icon.FrownTwoTone />
      <Icon.FunnelPlotTwoTone />
      <Icon.GiftTwoTone />
      <Icon.GoldTwoTone />
      <Icon.HddTwoTone />
      <Icon.HeartTwoTone />
      <Icon.HomeTwoTone />
      <Icon.HourglassTwoTone />
      <Icon.IdcardTwoTone />
      <Icon.InsuranceTwoTone />
      <Icon.InteractionTwoTone />
      <Icon.LayoutTwoTone />
      <Icon.LikeTwoTone />
      <Icon.LockTwoTone />
      <Icon.MailTwoTone />
      <Icon.MedicineBoxTwoTone />
      <Icon.MehTwoTone />
      <Icon.MessageTwoTone />
      <Icon.MobileTwoTone />
      <Icon.MoneyCollectTwoTone />
      <Icon.NotificationTwoTone />
      <Icon.PhoneTwoTone />
      <Icon.PictureTwoTone />
      <Icon.PlaySquareTwoTone />
      <Icon.PoundCircleTwoTone />
      <Icon.PrinterTwoTone />
      <Icon.ProfileTwoTone />
      <Icon.ProjectTwoTone />
      <Icon.PropertySafetyTwoTone />
      <Icon.PushpinTwoTone />
      <Icon.ReconciliationTwoTone />
      <Icon.RedEnvelopeTwoTone />
      <Icon.RestTwoTone />
      <Icon.RocketTwoTone />
      <Icon.SafetyCertificateTwoTone />
      <Icon.SaveTwoTone />
      <Icon.ScheduleTwoTone />
      <Icon.SecurityScanTwoTone />
      <Icon.SettingTwoTone />
      <Icon.ShopTwoTone />
      <Icon.ShoppingTwoTone />
      <Icon.SkinTwoTone />
      <Icon.SmileTwoTone />
      <Icon.SoundTwoTone />
      <Icon.StarTwoTone />
      <Icon.SwitcherTwoTone />
      <Icon.TabletTwoTone />
      <Icon.TagTwoTone />
      <Icon.TagsTwoTone />
      <Icon.ThunderboltTwoTone />
      <Icon.ToolTwoTone />
      <Icon.TrademarkCircleTwoTone />
      <Icon.TrophyTwoTone />
      <Icon.UnlockTwoTone />
      <Icon.UsbTwoTone />
      <Icon.VideoCameraTwoTone />
      <Icon.WalletTwoTone />
    </div>
  </div>
);

export const Outlined: Story = () => <OutlinedTemplate />;
Outlined.storyName = 'Outlined';

export const Solid: Story = () => <SolidTemplate />;
Solid.storyName = 'Solid';

export const TwoTone: Story = () => <TwoToneTemplate />;
TwoTone.storyName = 'Two Tone';
